### PR TITLE
Fixed some grammar.

### PR DESCRIPTION
**Pull request by geon**

### CODE REVIEW

**Comment by nyaray** [comment]
Have you thought about how this relates to #9 and #10?

It might be better if the changes you suggest are done in sync with those. I think it would make for a better experience if the docs and examples were in sync.

**Comment by geon** [comment]
I had no idea the other documents existed. I found some questionable english and corrected it. You do what you like with that.

**Comment by yhatt** [comment]
@geon Thanks for fix! I was sorry using poor English. 😓

**Comment by yhatt** [comment]
@nyaray OK. I will open new pull request to sync to changes of #9 (or #10).

**Pull request merged**
