### PR TITLE
Updates to language and grammar

### PR DESCRIPTION
**Pull request by ghazlewood**

### CODE REVIEW

**Comment by maxlevesque** [comment]
Obvious :+1:

**Comment by nyaray** [comment]
There's considerable overlap with #9 here, were you aware?

**Comment by yhatt** [comment]
@ghazlewood Thanks for update! :+1:
But it would conflict as @nyaray had said on above. Please wait a minute until merging #9.

**Comment by yhatt** [comment]
Once, I'll close..

**Pull request closed without merging**
