### PR TITLE
Implement slide navigation from menus

### PR DESCRIPTION
**Pull request by will-hart**
Implement navigating between slides using the context menu, re #26. Posting for feedback and some suggestions on how to implement keyboard shortcuts.

At the moment the menu accelerators don't do anything, see https://github.com/electron/electron/issues/2921 which I think is related.

I'll try to add Ctrl+PageUp, Ctrl+PageDown bindings in a second commit.

### CODE REVIEW

**Comment by will-hart** [comment]
@yhatt would you be ok for me to add a dependency to handle keyboard shortcuts:  https://www.npmjs.com/package/electron-localshortcut?

**Comment by yhatt** [comment]
@will-hart Hmm, I hardly recommend it. This is because keyboard shortcuts would work by adding menuitem to main menu.

Also for usability, I think we should add navigation commands in the main menu as well. How about this?

**Comment by will-hart** [comment]
Ok, no problems I'll have a go

**Comment by will-hart** [comment]
OK, done, 

`ctrl+PageUp` bindings didn't consistently apply - i.e. if you hit ctrl+pageup then ctrl+pgdown nothing happened for the second command. I've changed the keyboard shortcuts to `Shift+CmdOrCtrl+[` for previous and  `Shift+CmdOrCtrl+]`  for next.

**Pull request closed without merging**
